name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    env:
      REGISTRY_URL: ${{ vars.REGISTRY_URL }}
      REGISTRY_PROJECT: ${{ vars.REGISTRY_PROJECT }}
      REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to registry
        run: |        
          echo REGISTRY_PASSWORD | docker login '${{ vars.REGISTRY_URL }}' -u '${{ vars.REGISTRY_USERNAME }}' --password-stdin
      - name: Deploy stack to Docker Swarm
        run: |            
          $(SOURCE_ENVS) docker stack deploy --with-registry-auth \
            -c docker-compose.yml \
            -c docker-compose.yml \
            chill-on-da
