name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    env:
      REGISTRY_URL: ${{ vars.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      SSH_HOST: ${{ var.SSH_HOST }}
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to registry
        run: |        
          echo REGISTRY_PASSWORD | docker login '${{ vars.REGISTRY_URL }}' -u '${{ vars.REGISTRY_USERNAME }}' --password-stdin
      - name: Copy files to host
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "./docker-compose.yml"

      - name: Deploy stack to Docker Swarm
        run: |            
          $(TELEGRAM_TOKEN) docker stack deploy --with-registry-auth \
            -c docker-compose.yml \
            -c docker-compose.yml \
            chill-on-da
